### ISSUE TITLE
Is there any way to add PropertyNameCaseInsensitive = true, in FhirJsonSerializer

### ISSUE THREAD

**Issue by kalleo1996** [FirelyTeam/firely-docs-firely-net-sdk#67]
```
var sourceGenOptions = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true
};

string jsonString = JsonSerializer.Serialize(
    codeableConcept, typeof(CodeableConcept), sourceGenOptions);
JObject json = JObject.Parse(jsonString);

Console.WriteLine(json);
```
Currently, I am using the above code to add the PropertyNameCaseInsensitive option for JSON serialization. However, I am facing an issue when trying to convert this JSON object back to an HL7.FHIR.Resource and also want to use fhirSerilizer instead of json serilizer . My question is: does the FHIR serializer support an option similar to PropertyNameCaseInsensitive = true? If so, how can I configure it?

**Comment by vadi2** [comment]
What are you hoping to achieve by doing this?

**Comment by kalleo1996** [comment]
I am currently doing version updates when I am updating handlebar.net from 1.10.1 to 2.1.6 
Hl7.Fhir.R4 from  Version="1.4.0"  to 5.5.1 . I realized that case insensitivity that it used to have is no more . so inorder to restore case insensitivity I need this change . 
for futhure understanding refere the the following link that i have posted in handlebar.net repo end .

https://github.com/Handlebars-Net/Handlebars.Net/discussions/583

**Comment by kalleo1996** [comment]
actually I want to have case insensitivity while working with handlebar.net .

**Comment by kalleo1996** [comment]
Oh, that's alright. I just wanted to know if there's a setting like PropertyNameCaseInsensitive = true in the FHIR serializer. I'm looking for a way to resolve the case sensitivity issue I'm encountering with FHIR models in Handlebars.NET. If such a setting exists, it would allow the created FHIR resource to be accessed regardless of the case of the property names. If there's no existing implementation, that's okay too.
